### ISSUE TITLE
How to encode new line?

### ISSUE THREAD

**Issue by GAZ082** [mattn/twty#21]
Hey! I'm trying to automate some blog posts and when I try:

`echo "This is a test for a \n new line!" > tweet | twty -ff tweet`

The tweet just shows `\n`, not a new line.

Thanks!

**Comment by mattn** [comment]
I could tweet with new line using same way.

**Comment by zetamatta** [comment]
@GAZ082 Windows or Linux ? (CMD.EXE or bash ?)

**Comment by GAZ082** [comment]
@zetamatta oh sorry, Linux. The touched file is UTF-8 (checked with VIM).

**Comment by zetamatta** [comment]
@GAZ082 If you use bash, you might want to use `echo -e`. 

```sh
echo -e "This is a test for a \n new line!" > tweet && twty -ff tweet
```

**Comment by mattn** [comment]
Right. -e is required.

**Comment by GAZ082** [comment]
Yay thanks!
