### ISSUE TITLE
I can't seem to upload MP4 Videos using the -m flag

### ISSUE THREAD

**Issue by actionjack** [mattn/twty#25]
Love the app but I can't seem to upload MP4 Videos using the -m flag

**Comment by actionjack** [comment]
Thanks! the only problem with this is that it uses the file extension to detect the filetype. Unfortunately some times this is not know e.g. a temporary file generated using mktemp can we detect the [file type for when the extension is not know instead](https://golangcode.com/get-the-content-type-of-file/)?

**Comment by mattn** [comment]
Looks nice. I'll update to use it in later.

**Comment by actionjack** [comment]
Thank you!
