### ISSUE TITLE
Please fix the link on the Repository About

### ISSUE THREAD

**Issue by umireon** [mattn/twty#27]
<img width="253" alt="スクリーンショット 2021-11-03 16 38 09" src="https://user-images.githubusercontent.com/1067855/140023653-9e67821b-3d9c-40ab-823c-eac9648c8ccc.png">

http://mattn.kaoriya.net/

The scheme of this link is plaintext HTTP.
It would be great if the scheme were HTTPS.

https://mattn.kaoriya.net/

It confused me when I created the Homebrew Formula definition from repository information.

**Comment by mattn** [comment]
done. thank you
