### ISSUE TITLE
Error trying to sign into application first time

### ISSUE THREAD

**Issue by actionjack** [mattn/twty#28]
I get the redirected localhost when Authorize twty to access your account: 
https://127.0.0.1:9000/?oauth_token=XXXXXXX

this gives the following error: This site can’t be reached127.0.0.1 refused to connect.

**Comment by mattn** [comment]
Which OS do you use?

**Comment by actionjack** [comment]
MacOS

**Comment by actionjack** [comment]
it might be related to [this](https://github.com/orakaro/rainbowstream/issues/342)

**Comment by actionjack** [comment]
I've got developer access so I can produce my own keys but the key values don't match what's in the settings.json file.
