### ISSUE TITLE
Enhance color support

### ISSUE THREAD

**Issue by guersam** [mattn/twty#5]
Although coloring seems to be a good feature, the hard-coded colors hurt my eyes due to my light terminal background.

Suggestions are:
- [ ] Add an option to turn on/off coloring
- [ ] Detect current terminal color scheme

**Comment by guersam** [comment]
In addition, the colors goes weird in simple mode like this:
![screenshot from 2015-01-26 14 01 56](https://cloud.githubusercontent.com/assets/969120/5895465/e90fe7f8-a563-11e4-9338-5adca6a163c6.png)

**Comment by mattn** [comment]
Do you still have this issue?
