### ISSUE TITLE
Support of more than one Twitter account

### ISSUE THREAD

**Issue by ligurio** [mattn/twty#7]
twty is cool Twitter client, but I have two different Twitter account. twty can use only one in the same time. Please add support of more that one account.

**Workaround:**
Add to .profile:
```
function to { cp ~/.config/twty/settings-openvz.json ~/.config/twty/settings.json; twty $@; }
function te { cp ~/.config/twty/settings-estet.json ~/.config/twty/settings.json; twty $@; }
```
and use 'to' and 'te' commands in terminal with same options as twty has.

**Comment by mattn** [comment]
added option `-a` to use the account.

**Comment by ligurio** [comment]
Tested with two accounts and discovered in directory with config files:

~/.config/twty$ ls -1
settings-estet.json
settings-openvz.json
settingsestet.json
settingsopenvz.json

**Comment by mattn** [comment]
sorry fixed to handle `settings-XXX.json`.

**Comment by ligurio** [comment]
Feature works for me in new version. Thanks.

**Comment by mattn** [comment]
:+1:

**Comment by ligurio** [comment]
Many thanks for super fast resolving issue! :)
